#! /usr/bin/env python
# Irina Grigorescu 
# irina.grigorescu@cern.ch
# Jerome Belleman
# jerome.belleman@gmail.com

'''
A Kibana dashboard template tool
'''

import os
import sys
import argparse
import json

import mako.template
import mako.exceptions

def printtrace(trace):
    '''
    Print relevant trace
    '''

    relevant = False
    for line in trace.splitlines():
        if relevant:
            print line
        elif line.endswith('render_body'):
            print line
            relevant = True

    # Print last line if nothing was found to be relevant
    if not relevant:
        print line

def main():
    '''
    Main function
    '''

    # Check Arguments
    parser = argparse.ArgumentParser(description="A dashboard template tool.")
    parser.add_argument('directory', metavar='DIRECTORY',
                        help="dashboard template directory")
    parser.add_argument('output', metavar='OUTPUT', help="output file")
    parser.add_argument('-f', '--force', action='store_true',
                        help="write JSON file even if invalid (warn anyway)")
    args = parser.parse_args()
        
    # Load JSON template
    try:
        changeddir = False
        template = mako.template.Template(filename=args.directory + \
                                          '/template.json')
        cwd = os.getcwd()
        os.chdir(args.directory)
        changeddir = True
        body = template.render()
        os.chdir(cwd)
        changeddir = False
    except IOError, exc:
        print >> sys.stderr, exc
        return 1
    except Exception:
        if changeddir:
            os.chdir(cwd)
            changeddir = False
        printtrace(mako.exceptions.text_error_template().render())
        return 1

    # Check JSON validity
    try:
        json.loads(body)
    except ValueError, exc:
        print >> sys.stderr, exc
        if not args.force:
            return 1

    # Write output file
    try:
        with open(args.output, 'w') as fhl:
            fhl.write(body)
    except IOError, exc:
        print >> sys.stderr, exc
        return 1

if __name__ == '__main__':
    sys.exit(main())
