#! /usr/bin/env python
#     Irina Grigorescu 
#  irina.grigorescu@cern.ch

import os
import sys
import time
import string
import argparse
import yaml

from mako.template import Template

# File/Folder Parameters
OUTDIR = 'output'
TPLDIR = 'templates'

def main():
    global OUTDIR, TPLDIR

    # Check Arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('template', help = "template dashboard file")
    parser.add_argument('data', help = "data YAML file")
    args = parser.parse_args()
		
    try:
        # Load template
	with open(TPLDIR + "/" + args.template) as f:
	    template = f.read()
	f.close()

	# Load data
	with open(TPLDIR + "/" + args.data) as f:
	    data = yaml.load(f, Loader = yaml.BaseLoader)
	f.close()

        fileout = args.template + '.out.json'

        # Prepare data
        rows = [];
        for i in range(len(data[str(args.template)])):
            rows.append(data[str(args.template)][i]);
        print rows[0]['panel'][1]['title']
        #sys.exit(0)
        # Create output file
        myTemplate = Template(template);
        with open(OUTDIR + '/' + fileout, 'w') as f:
            f.write(myTemplate.render(rows = rows))
        f.close()

        print(myTemplate.render(rows = rows))

    except IOError, exc:
        printUsage()
        print >> sys.stderr, exc
        return 1


if __name__ == "__main__":
    sys.exit(main())

